"""
generate_sample_deck_v3.py — Generate a 5-slide sample deck using real dataset examples as style references.

Each slide is generated by gpt-5.4 using an actual HTML slide from the dataset as a style
reference, so the output inherits colors, typography, and layout patterns from the training data.

Topic: "Digital Transformation in Financial Services"

Output: pptmaker/sample_deck_v3.html
"""

from __future__ import annotations

import base64
import json
import os
import sys
import time
from pathlib import Path

from dotenv import load_dotenv
from openai import AzureOpenAI

load_dotenv()

ROOT     = Path(__file__).parent.parent
HTML_DIR = ROOT / "html_slides"
OUT      = ROOT / "sample_deck_v3.html"

W, H = 1280, 720

client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2024-12-01-preview",
    azure_endpoint="https://custom-data-maya-resource.cognitiveservices.azure.com/",
)

SYSTEM_PROMPT = f"""You are an expert front-end developer creating self-contained HTML/CSS presentation slides.

STRICT REQUIREMENTS:
1. Start with <!DOCTYPE html>
2. All CSS inside a <style> block in <head> — no external stylesheets
3. The slide root must be exactly {W}px wide and {H}px tall
4. The slide root must have: position: relative; overflow: hidden;
5. Use absolute positioning for all child elements
6. NO <script> tags
7. NO <img> tags — use CSS shapes, gradients, or Unicode for icons/illustrations
8. NO external URLs (no http:// or https:// anywhere)
9. System fonts only
10. Output ONLY the complete HTML document — no explanation, no markdown fences"""

SLIDES = [
    {
        "ref": "roland_berger_european_pe_outlook_1_slide_001",
        "brief": (
            "Title slide. Topic: 'Digital Transformation in Financial Services — 2025 Outlook'. "
            "LAYOUT (strict absolute positioning, no overlaps): "
            "  — Top-left: small caps label '2025 EDITION' at top:40px, left:80px, font-size:13px, letter-spacing:3px, color:#8a9099. "
            "  — Top-right: CSS bookmark logo placeholder (color:#1c78b0) with 'Client / Name' text. "
            "  — Left half (width:580px): headline at top:260px, left:80px, font-size:62px, font-weight:300, color:#ffffff, line-height:1.1. "
            "    Headline text exactly: 'Digital Transformation\\Ain Financial Services\\A— 2025 Outlook' (use <br> tags). "
            "  — Below headline (top:520px, left:80px): subtitle text 'How AI, platform modernisation, and embedded finance\\Aare reshaping growth, risk, and operating models.' "
            "    font-size:16px, color:#8a9099, line-height:1.5. Subtitle must NOT overlap the headline — leave at least 20px gap. "
            "  — Bottom-left: thin horizontal rule at top:670px, left:80px, width:60px, border-top:2px solid #1c78b0. "
            "  — Right half (left:700px): abstract CSS illustration — concentric arcs or a network of dots/lines in dark teal tones. "
            "  — Background: very dark navy #060e1a with subtle radial gradient lighter toward center-right. "
            "Do NOT include any text or element that overlaps another. "
            "Do NOT copy any structural chrome from the reference that doesn't fit this brief."
        ),
    },
    {
        "ref": "roland_berger_trend_compendium_2030___trend_5_dynamic_technology_and_innovation_slide_013",
        "brief": (
            "Consulting-style three-column content slide. "
            "BACKGROUND: white #ffffff. "
            "GLOBAL TYPOGRAPHY: font-family Arial, Helvetica, sans-serif only. All text color #1c2a3a unless specified. "
            "CONSISTENT LEFT MARGIN: 60px. RIGHT EDGE: 1220px. "
            ""
            "HEADER AREA (top:50px): "
            "  — Thin horizontal rule, left:60px, width:1160px, height:2px, background:#1c78b0. "
            "  — Kicker label below rule (top:62px, left:60px): 'FINANCIAL SERVICES OUTLOOK' font-size:10px, letter-spacing:2px, color:#1c78b0, text-transform:uppercase. "
            "  — Main headline (top:80px, left:60px, width:1100px): 'Three structural forces are redefining the competitive landscape in banking' "
            "    font-size:26px, font-weight:700, color:#1c2a3a, line-height:1.2. "
            ""
            "THREE COLUMNS (top:180px, each width:340px, height:440px): "
            "  Column 1 left:60px, Column 2 left:460px, Column 3 left:860px. "
            "  Each column: "
            "    — Top accent bar: width:40px, height:3px, background:#1c78b0, at column-left, top:0. "
            "    — Kicker (top:18px): uppercase label, font-size:10px, letter-spacing:1.5px, color:#1c78b0. "
            "    — Bold subhead (top:38px): font-size:17px, font-weight:700, color:#1c2a3a. "
            "    — Thin divider (top:68px): width:100%, height:1px, background:#d0d8e0. "
            "    — Three bullet rows (starting top:85px, spacing:56px each): "
            "        bullet dot (4px circle #1c78b0) at left:0, text starting left:14px, font-size:13px, color:#3a4a5a, line-height:1.4, max 2 lines. "
            "  Column 1 — Kicker: 'AI & AUTOMATION', Subhead: 'Intelligent Operations', "
            "    Bullets: 'Credit scoring models cut default rates by 18%' | 'Process automation saves 35% FTE costs in back office' | 'Real-time fraud detection at 99.2% precision'. "
            "  Column 2 — Kicker: 'OPEN FINANCE', Subhead: 'Platform Economics', "
            "    Bullets: 'API-first banks grow revenue 2.4× faster than legacy peers' | 'Embedded finance addressable market reaches $7tn by 2030' | 'Data monetisation emerging as new P&L line'. "
            "  Column 3 — Kicker: 'DIGITAL ASSETS', Subhead: 'New Value Rails', "
            "    Bullets: '12 G20 central banks piloting CBDCs in 2025' | 'Tokenised assets under management exceed $500bn' | 'DeFi integration reducing settlement time from T+2 to T+0'. "
            ""
            "FOOTER (top:670px, left:60px): font-size:10px, color:#9aa0a8. "
            "  'Sources: McKinsey Global Banking Report; BIS; Roland Berger analysis, 2025'. "
            ""
            "Do NOT copy structural chrome (sidebars, chapter icons, page numbers, logos) from the reference. "
            "Copy ONLY color palette, spacing rhythm, and typographic hierarchy from the reference."
        ),
    },
    {
        "ref": "roland_berger_trend_compendium_2050_technology_and_innovation_slide_010",
        "brief": (
            "Consulting-style two-column evidence slide with horizontal bar chart. "
            "BACKGROUND: white #ffffff. "
            "GLOBAL TYPOGRAPHY: font-family Arial, Helvetica, sans-serif. "
            ""
            "HEADER: "
            "  — Blue rule: position:absolute, top:40px, left:60px, width:1160px, height:2px, background:#1c78b0. "
            "  — Headline: position:absolute, top:52px, left:60px, width:820px, "
            "    font-size:22px, font-weight:700, color:#1c2a3a, line-height:1.25. "
            "    Text: 'AI adoption in banking leads all financial sub-sectors, driven by credit risk and compliance automation'. "
            "    AT 22px WITH LINE-HEIGHT 1.25 IN 820px WIDTH THIS WRAPS TO 3 LINES = 83px TALL. Headline ends at top:135px. "
            "  — Subtitle: position:absolute, top:148px, left:60px. "
            "    CRITICAL: top:148px is 13px below where the headline ends (135px). DO NOT place at top:110px. "
            "    Text: 'Share of firms actively deploying AI solutions, by sub-sector [%], 2025'. "
            "    font-size:12px, color:#6a7a8a, font-weight:400. "
            ""
            "LEFT PANEL — BAR CHART: all positions absolute from slide top. "
            "  Use these exact absolute top values for each row (label + bar together): "
            "    Banking:    label top:185px, bar top:202px. "
            "    Payments:   label top:280px, bar top:297px. "
            "    Insurance:  label top:375px, bar top:392px. "
            "    Asset Mgmt: label top:470px, bar top:487px. "
            "    RegTech:    label top:565px, bar top:582px. "
            "  All labels: left:60px, font-size:13px, font-weight:600, color:#1c2a3a. "
            "  Each bar: left:60px, width:440px (track), height:22px, background:#e8edf2, border-radius:2px. "
            "  Filled portion overlaid on track, same top/left/height, border-radius:2px: "
            "    Banking 68%    → width:299px, background:#1c5fa8. "
            "    Payments 61%   → width:268px, background:#1c78b0. "
            "    Insurance 54%  → width:238px, background:#4a9fd4. "
            "    Asset Mgmt 47% → width:207px, background:#7ab8e8. "
            "    RegTech 39%    → width:172px, background:#a8ccdf. "
            "  Percentage: position:absolute, left:510px, same top as bar, font-size:13px, font-weight:700, color:#1c2a3a, line-height:22px. "
            "  Axis line: top:608px, left:60px, width:440px, height:1px, background:#c0c8d0. "
            "  Axis labels (top:613px): '0%' left:60px | '25%' left:170px | '50%' left:280px | '75%' left:390px | '100%' left:494px. "
            "  font-size:10px, color:#9aa0a8. "
            ""
            "RIGHT PANEL — KEY INSIGHTS: "
            "  'KEY INSIGHTS' header: position:absolute, top:185px, left:760px, "
            "  font-size:11px, font-weight:700, color:#1c2a3a, letter-spacing:1.5px, text-transform:uppercase. "
            "  Card 1: position:absolute, top:210px, left:760px, width:460px, height:118px, "
            "    background:#f5f8fb, border-left:3px solid #1c78b0, padding:14px 18px, box-sizing:border-box. "
            "    Stat '3×' font-size:34px, font-weight:700, color:#1c5fa8. "
            "    Label 'faster credit decisions at banks using AI-assisted underwriting' font-size:12px, color:#4a5a6a, margin-top:6px. "
            "  Card 2: position:absolute, top:342px, left:760px, width:460px, height:118px, same style. "
            "    Stat '40%'. Label 'reduction in KYC onboarding cost through document automation'. "
            "  Card 3: position:absolute, top:474px, left:760px, width:460px, height:118px, same style. "
            "    Stat '$1.2tn'. Label 'projected AI-enabled revenue opportunity in financial services by 2030'. "
            ""
            "FOOTER: position:absolute, top:670px, left:60px, font-size:10px, color:#9aa0a8. "
            "  'Sources: Oliver Wyman AI in Finance Survey; Accenture; Roland Berger analysis, 2025'. "
            ""
            "Do NOT include sidebars, chapter icons, logos, page numbers, or dark backgrounds. "
            "Background: white #ffffff."
        ),
    },
    {
        "ref": "roland_berger_european_pe_outlook_1_slide_002",
        "brief": (
            "Consulting-style data callout slide with four large KPI boxes. "
            "BACKGROUND: white #ffffff. "
            "GLOBAL TYPOGRAPHY: font-family Arial, Helvetica, sans-serif. "
            ""
            "HEADER (top:50px, left:60px): "
            "  — Blue rule: left:60px, top:50px, width:1160px, height:2px, background:#1c78b0. "
            "  — Headline (top:62px): 'Financial services digitalisation is accelerating — key 2025 benchmarks' "
            "    font-size:26px, font-weight:700, color:#1c2a3a, width:900px. "
            ""
            "FOUR KPI CARDS in 2×2 grid (top:160px): "
            "  Card dimensions: width:510px, height:200px. "
            "  Card 1: left:60px, top:160px.   Card 2: left:610px, top:160px. "
            "  Card 3: left:60px, top:390px.   Card 4: left:610px, top:390px. "
            "  Each card: background:#f5f8fb, border-top:3px solid #1c78b0, padding:28px 32px, box-sizing:border-box. "
            "    — Big number: font-size:56px, font-weight:700, color:#1c5fa8, line-height:1. "
            "    — Short label (below number, ~8px gap): font-size:14px, color:#3a4a5a, font-weight:400. "
            "    — Trend indicator (bottom-right of card): small arrow + change text, font-size:12px. "
            "      Up arrow '▲' color:#2a8a4a, down arrow '▼' color:#c0392b. "
            "  Card 1: number '$4.2tn', label 'Global fintech market size', trend '▲ +18% YoY'. "
            "  Card 2: number '78%', label 'Banks with active AI programmes', trend '▲ +22pp vs 2023'. "
            "  Card 3: number '2.3×', label 'Digital-native bank revenue growth vs. incumbents', trend '▲ accelerating'. "
            "  Card 4: number '€890bn', label 'European open finance data flows by 2027', trend '▲ +31% YoY'. "
            ""
            "FOOTER (top:630px, left:60px): font-size:10px, color:#9aa0a8. "
            "  'Sources: Statista; McKinsey Global Institute; European Banking Authority, 2025'. "
            ""
            "No decorative backgrounds, no gradients on cards, no icons. Clean and data-forward."
        ),
    },
    {
        "ref": "deloitte_1q-2026-cfo-signals-survey_html_slide_002",
        "brief": (
            "Consulting-style executive summary / key findings slide. "
            "BACKGROUND: white #ffffff. "
            "GLOBAL TYPOGRAPHY: font-family Arial, Helvetica, sans-serif. "
            ""
            "HEADER (top:50px, left:60px): "
            "  — Blue rule: left:60px, top:50px, width:1160px, height:2px, background:#1c78b0. "
            "  — Label (top:62px): 'EXECUTIVE SUMMARY' font-size:10px, letter-spacing:2px, color:#1c78b0, text-transform:uppercase. "
            "  — Headline (top:80px): 'Five findings that demand immediate leadership attention' "
            "    font-size:26px, font-weight:700, color:#1c2a3a. "
            ""
            "FIVE FINDING ROWS (top:150px, left:60px, width:1160px): "
            "  Each row height:90px, separated by 1px horizontal rule color:#e0e6ec. "
            "  Row layout: "
            "    — Number badge: left:0, top:20px in row, width:32px, height:32px, background:#1c78b0, border-radius:50%, "
            "      text: row number, font-size:14px, font-weight:700, color:#ffffff, text-align:center, line-height:32px. "
            "    — Bold finding headline: left:50px, top:16px, font-size:15px, font-weight:700, color:#1c2a3a. "
            "    — Supporting sentence: left:50px, top:38px, width:1080px, font-size:13px, color:#4a5a6a, line-height:1.4. "
            "  Row 1: headline 'AI has become a board-level investment priority, not an IT experiment' "
            "    support '82% of financial services CEOs now include AI ROI in quarterly board reporting, up from 34% in 2023.' "
            "  Row 2: headline 'Automation is reshaping headcount planning across middle and back office' "
            "    support '60% of CFOs plan a net reduction in operations headcount within 18 months, offset by digital talent hiring.' "
            "  Row 3: headline 'Regulatory complexity is outpacing compliance investment at most institutions' "
            "    support 'ESG disclosure, DORA, and AI Act obligations will consume an estimated €4.2bn in compliance spend across EU banks in 2025.' "
            "  Row 4: headline 'The digital skills gap is the single largest barrier to transformation' "
            "    support 'Demand for AI engineers in financial services grew 3.1× in 2024; only 1 in 4 roles was filled within 90 days.' "
            "  Row 5: headline 'M&A is accelerating as incumbents acquire digital capability rather than build it' "
            "    support 'Fintech acquisition volume rose 34% YoY; median deal size increased to $280mn as targets mature.' "
            ""
            "FOOTER (top:670px, left:60px): font-size:10px, color:#9aa0a8. "
            "  'Sources: Deloitte CFO Signals Survey Q1 2026; Oliver Wyman; Roland Berger executive interviews'. "
            ""
            "Do NOT use colored row backgrounds. Clean white rows, ruled lines, blue number badges only."
        ),
    },
]


def read_ref(slide_id: str) -> str:
    path = HTML_DIR / f"{slide_id}.html"
    return path.read_text(encoding="utf-8", errors="ignore")


def generate_slide(brief: str, ref_html: str, idx: int) -> str:
    print(f"  Generating slide {idx+1}/5 ...", end=" ", flush=True)

    user_content = (
        f"Create a new {W}×{H}px HTML/CSS presentation slide.\n\n"
        f"SLIDE BRIEF:\n{brief}\n\n"
        f"STYLE REFERENCE (use this HTML as your visual style guide — copy the color palette, "
        f"font choices, spacing conventions, and CSS patterns, but generate entirely new content "
        f"matching the brief above):\n\n"
        f"{ref_html}"
    )

    resp = client.chat.completions.create(
        model="gpt-5.4",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_content},
        ],
        max_completion_tokens=8192,
    )

    html = resp.choices[0].message.content or ""
    # Strip markdown fences if present
    import re
    m = re.search(r"```(?:html)?\s*(<!DOCTYPE.*?</html>)\s*```", html, re.DOTALL | re.IGNORECASE)
    if m:
        html = m.group(1).strip()
    else:
        m = re.search(r"(<!DOCTYPE.*?</html>)", html, re.DOTALL | re.IGNORECASE)
        if m:
            html = m.group(1).strip()

    truncated = "</html>" not in html.lower()
    print("OK" + (" [truncated]" if truncated else ""))
    return html


def wrap_deck(slides_html: list[str]) -> str:
    cards = ""
    for i, html in enumerate(slides_html):
        encoded = html.replace("&", "&amp;").replace("<", "&#60;").replace(">", "&#62;").replace('"', "&quot;")
        cards += f"""
    <div class="slide-card" id="s{i}" style="display:{'block' if i==0 else 'none'}">
      <div class="label">Slide {i+1} of {len(slides_html)}</div>
      <iframe srcdoc="{encoded}" width="{W}" height="{H}" scrolling="no" frameborder="0"></iframe>
    </div>"""

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Sample Deck v3 — Digital Transformation in Financial Services</title>
<style>
  body {{ margin: 0; background: #1a1a2e; display: flex; flex-direction: column;
         align-items: center; justify-content: center; min-height: 100vh;
         font-family: Arial, sans-serif; }}
  h1 {{ color: #ccc; font-size: 14px; font-weight: 400; margin: 16px 0 8px; letter-spacing: 1px; text-transform: uppercase; }}
  .slide-card {{ text-align: center; }}
  .label {{ color: #666; font-size: 12px; margin-bottom: 8px; }}
  iframe {{ display: block; border-radius: 4px; box-shadow: 0 8px 40px rgba(0,0,0,0.6); }}
  .nav {{ display: flex; gap: 16px; margin-top: 20px; }}
  button {{ background: #2a2a4a; border: 1px solid #444; color: #ccc; padding: 8px 24px;
            border-radius: 4px; cursor: pointer; font-size: 13px; }}
  button:hover {{ background: #3a3a6a; }}
  .dots {{ display: flex; gap: 8px; align-items: center; }}
  .dot {{ width: 8px; height: 8px; border-radius: 50%; background: #444; cursor: pointer; }}
  .dot.active {{ background: #7b8cde; }}
</style>
</head>
<body>
<h1>Digital Transformation in Financial Services — 2025 Outlook</h1>
{cards}
<div class="nav">
  <button onclick="move(-1)">&#8592; Prev</button>
  <div class="dots" id="dots"></div>
  <button onclick="move(1)">Next &#8594;</button>
</div>
<script>
  var cur = 0, total = {len(slides_html)};
  var dots = document.getElementById('dots');
  for (var i = 0; i < total; i++) {{
    var d = document.createElement('div');
    d.className = 'dot' + (i===0?' active':'');
    d.dataset.i = i;
    d.onclick = function() {{ go(+this.dataset.i); }};
    dots.appendChild(d);
  }}
  function go(n) {{
    document.getElementById('s'+cur).style.display = 'none';
    dots.children[cur].classList.remove('active');
    cur = (n + total) % total;
    document.getElementById('s'+cur).style.display = 'block';
    dots.children[cur].classList.add('active');
  }}
  function move(d) {{ go(cur+d); }}
  document.addEventListener('keydown', function(e) {{
    if (e.key==='ArrowRight') move(1);
    if (e.key==='ArrowLeft')  move(-1);
  }});
</script>
</body>
</html>"""


def main():
    print("Generating sample deck v3 — Digital Transformation in Financial Services")
    print(f"Output: {OUT}\n")

    slides_html = []
    for i, slide_def in enumerate(SLIDES):
        ref_html = read_ref(slide_def["ref"])
        html = generate_slide(slide_def["brief"], ref_html, i)
        slides_html.append(html)
        if i < len(SLIDES) - 1:
            time.sleep(1)

    deck = wrap_deck(slides_html)
    OUT.write_text(deck, encoding="utf-8")
    print(f"\nDone — {OUT}")


if __name__ == "__main__":
    main()
